(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DEG=Math.PI/180, RAD=180/Math.PI, TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const norm360=v=>(v%360+360)%360;
const norm180=v=>((v+180)%360+360)%360-180;
const canvas=$('#skyCanvas'), ctx=canvas.getContext('2d',{alpha:false});
const sketch=$('#objectSketch'), sctx=sketch.getContext('2d');
let objectImage=$('#objectImage'), objectImageCaption=$('#objectImageCaption');
// Defensive fallback for older/cached HTML: create the image UI if it is missing.
if(!objectImage||!objectImageCaption){
  let media=sketch.closest('.object-media');
  if(!media){media=document.createElement('div');media.className='object-media';sketch.before(media);media.appendChild(sketch)}
  if(!objectImage){objectImage=document.createElement('img');objectImage.id='objectImage';objectImage.className='object-image';objectImage.alt='';objectImage.hidden=true;objectImage.decoding='async';media.prepend(objectImage)}
  if(!objectImageCaption){objectImageCaption=document.createElement('div');objectImageCaption.id='objectImageCaption';objectImageCaption.className='object-image-caption';objectImageCaption.hidden=true;media.appendChild(objectImageCaption)}
}
const state={mode:'horizontal',centerLon:180,centerLat:35,fov:70,magLimit:5.5,starScale:1,grid:true,constellations:true,dso:true,labels:true,milkyWay:true,hideBelow:true,cardinals:true,night:false,lat:52.52,lon:13.405,time:new Date(),playing:false,selected:null,pointer:null};
let dpr=1,w=0,h=0,focal=1,forward=[1,0,0],right=[0,1,0],up=[0,0,1],hitTargets=[],drag=null,pinch=null,toastTimer=0,lastFrame=performance.now(),detailImageToken=0;
const starByName=new Map(STAR_DATA.map(s=>[s.name.toLowerCase(),s]));
STAR_DATA.forEach(s=>{if(s.alias)starByName.set(s.alias.toLowerCase(),s)});


function imageKey(value){return String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'')}
function imageSlug(value){return String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
function imageLookupNames(o){const names=[o.id,o.name,...(o.aliases||[])].filter(Boolean),out=[];for(const name of names){out.push(name);const compact=imageKey(name);if(/^m\d+$/.test(compact))out.push(`messier${compact.slice(1)}`);if(/^ngc\d+$/.test(compact))out.push(`ngc ${compact.slice(3)}`)}return [...new Set(out)]}
function indexedObjectImages(o){const index=globalThis.DSO_IMAGE_INDEX||{},found=[];for(const name of imageLookupNames(o)){for(const entry of index[imageKey(name)]||[]){if(!found.some(item=>item.src===entry.src))found.push(entry)}}return found}
function directObjectImageCandidates(o){const exts=['webp','jpg','jpeg','png','avif'],slugs=[imageKey(o.id),imageSlug(o.id)].filter(Boolean),found=[];for(const slug of [...new Set(slugs)])for(const ext of exts)found.push({src:`images/dso/${slug}.${ext}`,title:o.name||o.id,alt:`Local astronomical image of ${o.name||o.id}`,credit:'Local offline image',source:'',license:''});return found}
function setImageCaption(entry){const parts=[entry.title,entry.credit,entry.license].filter(Boolean);objectImageCaption.textContent=parts.join(' · ');objectImageCaption.hidden=!parts.length;if(entry.source){const link=document.createElement('a');link.href=entry.source;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Source';objectImageCaption.append(' · ',link)}}
function showObjectVisual(o){const token=++detailImageToken;objectImage.hidden=true;objectImage.removeAttribute('src');objectImageCaption.hidden=true;objectImageCaption.textContent='';sketch.hidden=false;if(o.kind==='star'){drawSketch(o);return}const indexed=indexedObjectImages(o),candidates=[...indexed,...directObjectImageCandidates(o).filter(candidate=>!indexed.some(entry=>entry.src===candidate.src))];let i=0;const tryNext=()=>{if(token!==detailImageToken)return;if(i>=candidates.length){objectImage.hidden=true;sketch.hidden=false;objectImageCaption.hidden=true;drawSketch(o);return}const entry=candidates[i++];objectImage.onload=()=>{if(token!==detailImageToken)return;sketch.hidden=true;objectImage.hidden=false;objectImage.alt=entry.alt||`Astronomical image of ${o.name||o.id}`;setImageCaption(entry)};objectImage.onerror=tryNext;objectImage.src=entry.src};tryNext()}

function resize(){dpr=Math.min(2,window.devicePixelRatio||1);w=canvas.clientWidth;h=canvas.clientHeight;canvas.width=Math.max(1,Math.round(w*dpr));canvas.height=Math.max(1,Math.round(h*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);render();}
function sph(lon,lat){const l=lon*DEG,b=lat*DEG,c=Math.cos(b);return[c*Math.cos(l),c*Math.sin(l),Math.sin(b)]}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function normalize(v){const m=Math.hypot(...v)||1;return v.map(x=>x/m)}
function camera(){forward=sph(state.centerLon,state.centerLat);right=normalize(cross([0,0,1],forward));if(Math.hypot(...right)<.1)right=[0,1,0];up=normalize(cross(forward,right));focal=(h*.5)/Math.tan(state.fov*.5*DEG)}
function eqVec(raHours,dec){return sph(raHours*15,dec)}
function julian(date){return date.getTime()/86400000+2440587.5}
function lstDeg(date=state.time){return norm360(280.46061837+360.98564736629*(julian(date)-2451545)+state.lon)}
function eqToHorizontal(raHours,dec){const H=norm180(lstDeg()-raHours*15)*DEG,d=dec*DEG,p=state.lat*DEG;const east=-Math.cos(d)*Math.sin(H);const north=Math.sin(d)*Math.cos(p)-Math.cos(d)*Math.cos(H)*Math.sin(p);const zenith=Math.sin(d)*Math.sin(p)+Math.cos(d)*Math.cos(H)*Math.cos(p);return[north,east,zenith]}
function horizontalToEq(v){const north=v[0],east=v[1],zenith=v[2],p=state.lat*DEG;const sd=clamp(north*Math.cos(p)+zenith*Math.sin(p),-1,1);const dec=Math.asin(sd);const H=Math.atan2(-east,zenith*Math.cos(p)-north*Math.sin(p));return{ra:norm360(lstDeg()-H*RAD)/15,dec:dec*RAD}}
function objectVec(o){return state.mode==='equatorial'?eqVec(o.ra,o.dec):eqToHorizontal(o.ra,o.dec)}
function project(v){const z=dot(v,forward);if(z<=.025)return null;const x=w/2+focal*dot(v,right)/z,y=h/2-focal*dot(v,up)/z;if(x<-120||x>w+120||y<-120||y>h+120)return null;return{x,y,z}}
function unproject(x,y){const v=normalize([forward[0]+right[0]*(x-w/2)/focal-up[0]*(y-h/2)/focal,forward[1]+right[1]*(x-w/2)/focal-up[1]*(y-h/2)/focal,forward[2]+right[2]*(x-w/2)/focal-up[2]*(y-h/2)/focal]);return v}
function vecLonLat(v){return{lon:norm360(Math.atan2(v[1],v[0])*RAD),lat:Math.asin(clamp(v[2],-1,1))*RAD}}
function formatRA(ra){let hh=Math.floor(ra),mm=Math.floor((ra-hh)*60),ss=(((ra-hh)*60-mm)*60).toFixed(1);if(+ss>=60){ss='0.0';mm++}if(mm>=60){mm=0;hh=(hh+1)%24}return`${String(hh).padStart(2,'0')}h ${String(mm).padStart(2,'0')}m ${String(ss).padStart(4,'0')}s`}
function formatDec(dec){const s=dec<0?'−':'+';let a=Math.abs(dec),dd=Math.floor(a),mm=Math.floor((a-dd)*60),ss=Math.round((((a-dd)*60)-mm)*60);if(ss>=60){ss=0;mm++}return`${s}${String(dd).padStart(2,'0')}° ${String(mm).padStart(2,'0')}′ ${String(ss).padStart(2,'0')}″`}
function bvColor(bv){bv=clamp(bv??.4,-.4,2);let r,g,b;if(bv<0){r=180+70*(bv+.4)/.4;g=205+45*(bv+.4)/.4;b=255}else if(bv<.4){r=245+10*bv/.4;g=245;b=255-25*bv/.4}else if(bv<1.2){r=255;g=245-75*(bv-.4)/.8;b=230-120*(bv-.4)/.8}else{r=255;g=170-55*(bv-1.2)/.8;b=110-60*(bv-1.2)/.8}return`rgb(${r|0},${g|0},${b|0})`}
function altitude(o){return Math.asin(clamp(eqToHorizontal(o.ra,o.dec)[2],-1,1))*RAD}
function clear(){let g=ctx.createRadialGradient(w*.5,h*.45,0,w*.5,h*.45,Math.max(w,h)*.72);if(state.night){g.addColorStop(0,'#130404');g.addColorStop(1,'#020000')}else{g.addColorStop(0,'#08162d');g.addColorStop(.58,'#030914');g.addColorStop(1,'#010308')}ctx.fillStyle=g;ctx.fillRect(0,0,w,h);if(state.mode==='horizontal'){const alt=state.centerLat;const glow=clamp((10-alt)/35,0,.32);if(glow>0){let a=ctx.createLinearGradient(0,h*.55,0,h);a.addColorStop(0,'rgba(36,60,82,0)');a.addColorStop(1,`rgba(48,62,72,${glow})`);ctx.fillStyle=a;ctx.fillRect(0,0,w,h)}}}
function drawPolyline(points,style,width=1,dash=[]){ctx.save();ctx.strokeStyle=style;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();let prev=null,started=false;for(const v of points){const p=project(v);if(!p){prev=null;started=false;continue}if(prev&&Math.hypot(p.x-prev.x,p.y-prev.y)>w*.35){started=false}if(!started){ctx.moveTo(p.x,p.y);started=true}else ctx.lineTo(p.x,p.y);prev=p}ctx.stroke();ctx.restore()}
function galToEq(l,b){const lr=l*DEG,br=b*DEG,gv=[Math.cos(br)*Math.cos(lr),Math.cos(br)*Math.sin(lr),Math.sin(br)];const m=[[-.0548755604,.4941094279,-.8676661490],[-.8734370902,-.4448296300,-.1980763734],[-.4838350155,.7469822445,.4559837762]];return[m[0][0]*gv[0]+m[0][1]*gv[1]+m[0][2]*gv[2],m[1][0]*gv[0]+m[1][1]*gv[1]+m[1][2]*gv[2],m[2][0]*gv[0]+m[2][1]*gv[1]+m[2][2]*gv[2]]}
function eqVectorToMode(v){if(state.mode==='equatorial')return v;const ll=vecLonLat(v);return eqToHorizontal(ll.lon/15,ll.lat)}
function drawMilkyWay(){if(!state.milkyWay)return;for(let b=-14;b<=14;b+=4){const pts=[];for(let l=0;l<=360;l+=2)pts.push(eqVectorToMode(galToEq(l,b)));const alpha=.018+(14-Math.abs(b))*.0025;drawPolyline(pts,`rgba(105,150,190,${alpha})`,Math.max(2,8-Math.abs(b)*.3))}const pts=[];for(let l=0;l<=360;l+=2)pts.push(eqVectorToMode(galToEq(l,0)));drawPolyline(pts,'rgba(136,178,220,.12)',1)}
function drawGrid(){if(!state.grid)return;const color='rgba(119,158,194,.16)',major='rgba(119,158,194,.24)';if(state.mode==='equatorial'){for(let ra=0;ra<360;ra+=15){let pts=[];for(let dec=-89;dec<=89;dec+=2)pts.push(sph(ra,dec));drawPolyline(pts,ra%45===0?major:color,ra%45===0?1:.6)}for(let dec=-75;dec<=75;dec+=15){let pts=[];for(let ra=0;ra<=360;ra+=2)pts.push(sph(ra,dec));drawPolyline(pts,dec===0?major:color,dec===0?1:.6)}}else{for(let az=0;az<360;az+=15){let pts=[];for(let alt=-5;alt<=90;alt+=2)pts.push(sph(az,alt));drawPolyline(pts,az%45===0?major:color,az%45===0?1:.6)}for(let alt=0;alt<=75;alt+=15){let pts=[];for(let az=0;az<=360;az+=2)pts.push(sph(az,alt));drawPolyline(pts,alt===0?'rgba(246,201,120,.42)':color,alt===0?1.2:.6)}}}
function drawCardinals(){if(state.mode!=='horizontal'||!state.cardinals)return;const labels=[['N',0],['NE',45],['E',90],['SE',135],['S',180],['SW',225],['W',270],['NW',315]];ctx.save();ctx.font='600 10px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';for(const [txt,az] of labels){const p=project(sph(az,0));if(p){ctx.fillStyle=txt.length===1?'rgba(246,201,120,.9)':'rgba(170,185,204,.55)';ctx.fillText(txt,p.x,p.y-9)}}ctx.restore()}
function drawConstellations(){if(!state.constellations)return;ctx.save();ctx.strokeStyle='rgba(125,151,255,.28)';ctx.lineWidth=.9;ctx.setLineDash([3,4]);ctx.font='9px system-ui';ctx.fillStyle='rgba(150,170,230,.62)';for(const [name,lines] of Object.entries(CONSTELLATION_LINES)){let cx=0,cy=0,count=0;for(const [a,b] of lines){const sa=starByName.get(a.toLowerCase()),sb=starByName.get(b.toLowerCase());if(!sa||!sb)continue;if(state.mode==='horizontal'&&state.hideBelow&&altitude(sa)<0&&altitude(sb)<0)continue;const pa=project(objectVec(sa)),pb=project(objectVec(sb));if(pa&&pb&&Math.hypot(pa.x-pb.x,pa.y-pb.y)<w*.35){ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();cx+=pa.x+pb.x;cy+=pa.y+pb.y;count+=2}}if(state.labels&&count){ctx.fillText(name,cx/count+5,cy/count-5)}}ctx.restore()}
function drawStars(){for(const s of STAR_DATA){if(s.mag>state.magLimit)continue;const alt=state.mode==='horizontal'?altitude(s):90;if(state.mode==='horizontal'&&state.hideBelow&&alt<0)continue;const p=project(objectVec(s));if(!p)continue;const base=Math.max(.45,(4.25-(s.mag+1.5)*.52)*state.starScale);const r=Math.max(.35,base*Math.min(1.25,Math.sqrt(p.z)));const color=bvColor(s.bv);if(s.mag<1.7){const gr=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,Math.max(3,r*4));gr.addColorStop(0,color);gr.addColorStop(.25,color.replace('rgb','rgba').replace(')',',.32)'));gr.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=gr;ctx.beginPath();ctx.arc(p.x,p.y,Math.max(3,r*4),0,TAU);ctx.fill()}ctx.fillStyle=color;ctx.globalAlpha=clamp(1-(s.mag-state.magLimit+1)*.08,.35,1);ctx.beginPath();ctx.arc(p.x,p.y,Math.max(.35,r),0,TAU);ctx.fill();ctx.globalAlpha=1;hitTargets.push({x:p.x,y:p.y,r:Math.max(7,r+3),object:{...s,kind:'star',type:'Star',id:s.name}});if(state.labels&&(s.mag<2.55||state.fov<25)){ctx.font=s.mag<1.2?'600 11px system-ui':'10px system-ui';ctx.fillStyle='rgba(220,232,247,.78)';ctx.fillText(s.name,p.x+r+4,p.y-3)}}}
function dsoGlyph(o,p,size,alpha=1){const t=o.type.toLowerCase();ctx.save();ctx.translate(p.x,p.y);ctx.globalAlpha=alpha;ctx.strokeStyle=t.includes('galaxy')?'#aa91ff':t.includes('cluster')?'#62d8ff':'#f6c978';ctx.fillStyle='rgba(0,0,0,.18)';ctx.lineWidth=1;if(t.includes('galaxy')){ctx.rotate(-.35);ctx.beginPath();ctx.ellipse(0,0,size*1.45,size*.55,0,0,TAU);ctx.stroke();ctx.beginPath();ctx.arc(0,0,Math.max(1.2,size*.16),0,TAU);ctx.fillStyle=ctx.strokeStyle;ctx.fill()}else if(t.includes('globular')){ctx.beginPath();ctx.arc(0,0,size,0,TAU);ctx.stroke();ctx.beginPath();ctx.moveTo(-size,0);ctx.lineTo(size,0);ctx.moveTo(0,-size);ctx.lineTo(0,size);ctx.stroke()}else if(t.includes('open cluster')){for(let i=0;i<7;i++){const a=i*2.399,r=size*(.2+.7*((i*37)%10)/10);ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(Math.cos(a)*r-1,Math.sin(a)*r-1,2,2)}}else if(t.includes('nebula')||t.includes('remnant')){ctx.beginPath();for(let i=0;i<8;i++){const a=i*TAU/8,rr=size*(i%2?1:.68),x=Math.cos(a)*rr,y=Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}else{ctx.beginPath();ctx.rect(-size*.65,-size*.65,size*1.3,size*1.3);ctx.stroke()}ctx.restore()}
function drawDSOs(){if(!state.dso)return;for(const o of DSO_DATA){const alt=state.mode==='horizontal'?altitude(o):90;if(state.mode==='horizontal'&&state.hideBelow&&alt<0)continue;const p=project(objectVec(o));if(!p)continue;const size=clamp(3.5+(70/state.fov),4,10);dsoGlyph(o,p,size,.9);hitTargets.push({x:p.x,y:p.y,r:Math.max(10,size+4),object:{...o,kind:'dso'}});if(state.labels&&(state.fov<85||o.mag<=6.1)){ctx.font='600 10px system-ui';ctx.fillStyle='rgba(186,204,224,.82)';ctx.fillText(o.id,p.x+size+4,p.y+3)}}}
function drawReticle(){ctx.save();ctx.strokeStyle='rgba(98,216,255,.28)';ctx.lineWidth=.7;ctx.beginPath();ctx.arc(w/2,h/2,7,0,TAU);ctx.moveTo(w/2-13,h/2);ctx.lineTo(w/2-5,h/2);ctx.moveTo(w/2+5,h/2);ctx.lineTo(w/2+13,h/2);ctx.moveTo(w/2,h/2-13);ctx.lineTo(w/2,h/2-5);ctx.moveTo(w/2,h/2+5);ctx.lineTo(w/2,h/2+13);ctx.stroke();ctx.restore()}
function render(){if(!w||!h)return;camera();hitTargets=[];clear();drawMilkyWay();drawGrid();drawCardinals();drawConstellations();drawStars();drawDSOs();drawReticle();updateStatus()}
function updateStatus(){const center=state.mode==='equatorial'?{ra:state.centerLon/15,dec:state.centerLat}:horizontalToEq(sph(state.centerLon,state.centerLat));const modeText=state.mode==='equatorial'?`RA ${formatRA(center.ra)} · Dec ${formatDec(center.dec)}`:`Az ${state.centerLon.toFixed(1)}° · Alt ${state.centerLat.toFixed(1)}°`;$('#coordReadout').textContent=modeText;$('#fovReadout').textContent=`FoV ${state.fov.toFixed(state.fov<10?1:0)}°`;$('#dateTimeValue').textContent=state.time.toLocaleString([], {dateStyle:'medium',timeStyle:'short'});$('#lstValue').textContent=`LST ${(lstDeg()/15).toFixed(2)}h`;$('#clockLabel').textContent=Math.abs(state.time-Date.now())<60000?'Now':state.time.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}
function setMode(mode){if(mode===state.mode)return;const c=sph(state.centerLon,state.centerLat);if(mode==='equatorial'){const eq=horizontalToEq(c);state.centerLon=eq.ra*15;state.centerLat=eq.dec}else{const v=eqToHorizontal(state.centerLon/15,state.centerLat),ll=vecLonLat(v);state.centerLon=ll.lon;state.centerLat=ll.lat}state.mode=mode;$$('#modeSelect button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#modeButton').classList.toggle('active',mode==='equatorial');render();saveHash()}
function focusObject(o,open=true){const targetModeVec=objectVec(o),ll=vecLonLat(targetModeVec);animateView(ll.lon,ll.lat,Math.min(state.fov,22));state.selected=o;if(open)showDetails(o)}
function animateView(lon,lat,fov=state.fov){const start={lon:state.centerLon,lat:state.centerLat,fov:state.fov},dl=norm180(lon-start.lon),t0=performance.now(),dur=650;function tick(now){const t=clamp((now-t0)/dur,0,1),e=1-Math.pow(1-t,3);state.centerLon=norm360(start.lon+dl*e);state.centerLat=start.lat+(lat-start.lat)*e;state.fov=start.fov+(fov-start.fov)*e;render();if(t<1)requestAnimationFrame(tick);else saveHash()}requestAnimationFrame(tick)}
function showDetails(o){const isStar=o.kind==='star';const alt=altitude(o),aliases=isStar?o.alias:(o.aliases||[]).join(' · ');$('#detailsContent').innerHTML=`<p class="object-kicker">${isStar?'Bright star':o.type}</p><h2 class="object-title">${isStar?o.name:(o.name||o.id)}</h2><p class="object-aliases">${isStar?aliases:`${o.id}${aliases?' · '+aliases:''}`}</p><div class="detail-grid"><div><span>Right ascension</span><strong>${formatRA(o.ra)}</strong></div><div><span>Declination</span><strong>${formatDec(o.dec)}</strong></div><div><span>Magnitude</span><strong>${Number.isFinite(o.mag)?o.mag.toFixed(2):'—'}</strong></div><div><span>Constellation</span><strong>${o.con||'—'}</strong></div><div><span>Altitude now</span><strong>${alt.toFixed(1)}°</strong></div><div><span>${isStar?'B−V colour index':'Angular size'}</span><strong>${isStar?(o.bv??'—'):o.size}</strong></div>${isStar?'':`<div><span>Distance</span><strong>${o.distance||'—'}</strong></div><div><span>Catalog</span><strong>Local offline pack</strong></div>`}</div><p class="object-description">${isStar?`A bright star in ${o.con}. Its plotted colour is estimated from the catalogued B−V colour index.`:o.description}</p><div class="detail-actions"><button id="centerObjectButton">Centre and zoom</button><button id="closeDetailsButton">Close</button></div>`;$('#detailsPanel').classList.add('open');$('#detailsPanel').setAttribute('aria-hidden','false');showObjectVisual(o);$('#centerObjectButton').onclick=()=>focusObject(o,false);$('#closeDetailsButton').onclick=()=>closePanel('detailsPanel')}
function drawSketch(o){const W=sketch.width,H=sketch.height;sctx.clearRect(0,0,W,H);const g=sctx.createRadialGradient(W*.5,H*.52,0,W*.5,H*.52,W*.55);g.addColorStop(0,state.night?'#370909':'#13264a');g.addColorStop(1,'#03060d');sctx.fillStyle=g;sctx.fillRect(0,0,W,H);let seed=[...((o.id||o.name)||'object')].reduce((a,c)=>a+c.charCodeAt(0),1);const rnd=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);for(let i=0;i<90;i++){const x=rnd()*W,y=rnd()*H,r=rnd()*1.1+.2;sctx.fillStyle=`rgba(220,235,255,${.15+rnd()*.55})`;sctx.beginPath();sctx.arc(x,y,r,0,TAU);sctx.fill()}if(o.kind==='star'){const r=34;const c=bvColor(o.bv);const q=sctx.createRadialGradient(W/2,H/2,0,W/2,H/2,r*2.8);q.addColorStop(0,'white');q.addColorStop(.16,c);q.addColorStop(1,'rgba(255,255,255,0)');sctx.fillStyle=q;sctx.beginPath();sctx.arc(W/2,H/2,r*2.8,0,TAU);sctx.fill()}else{const t=o.type.toLowerCase();sctx.save();sctx.translate(W/2,H/2);if(t.includes('galaxy')){sctx.rotate(-.28);for(let i=7;i>0;i--){sctx.fillStyle=`rgba(160,145,255,${.025+i*.018})`;sctx.beginPath();sctx.ellipse(0,0,i*19,i*6.2,0,0,TAU);sctx.fill()}sctx.fillStyle='#f3ebd4';sctx.beginPath();sctx.arc(0,0,5,0,TAU);sctx.fill()}else if(t.includes('cluster')){for(let i=0;i<110;i++){const a=rnd()*TAU,r=Math.pow(rnd(),.65)*70;sctx.fillStyle=`rgba(205,230,255,${.2+rnd()*.75})`;sctx.fillRect(Math.cos(a)*r,Math.sin(a)*r,rnd()*2+1,rnd()*2+1)}}else{for(let i=0;i<7;i++){sctx.strokeStyle=`rgba(100,210,255,${.05+i*.035})`;sctx.lineWidth=8;sctx.beginPath();sctx.ellipse(0,0,25+i*10,16+i*6,i*.19,0,TAU);sctx.stroke()}}sctx.restore()}sctx.fillStyle='rgba(255,255,255,.5)';sctx.font='11px system-ui';sctx.fillText('SCHEMATIC OFFLINE VIEW',16,H-15)}
function search(query){const q=query.trim().toLowerCase();if(!q)return[];const coord=parseCoords(q);if(coord)return[{kind:'coords',name:`RA ${coord.ra.toFixed(3)}h, Dec ${coord.dec.toFixed(3)}°`,...coord}];const all=[...STAR_DATA.map(x=>({...x,kind:'star',id:x.name})),...DSO_DATA.map(x=>({...x,kind:'dso'}))];return all.map(o=>{const text=[o.id,o.name,o.alias,...(o.aliases||[]),o.con,o.type].filter(Boolean).join(' ').toLowerCase();let score=text===q?100:text.startsWith(q)?70:text.includes(q)?40:0;if((o.id||'').toLowerCase()===q)score=110;return{o,score}}).filter(x=>x.score).sort((a,b)=>b.score-a.score||((a.o.mag??99)-(b.o.mag??99))).slice(0,8).map(x=>x.o)}
function parseCoords(q){const m=q.match(/^\s*(\d{1,2}(?:\.\d+)?)\s*[, ]\s*([+-]?\d{1,2}(?:\.\d+)?)\s*$/);if(!m)return null;let a=+m[1],d=+m[2];if(Math.abs(d)>90)return null;return{ra:a>24?a/15:a,dec:d}}
function showSearchResults(items){const box=$('#searchResults');if(!items.length){box.classList.remove('open');box.innerHTML='';return}box.innerHTML=items.map((o,i)=>`<button class="search-result${i===0?' active':''}" data-index="${i}" role="option"><strong>${o.name||o.id}</strong><span>${o.kind==='coords'?'Coordinates':o.kind==='star'?`Star · mag ${o.mag}`:`${o.id} · ${o.type}`}</span></button>`).join('');box.classList.add('open');$$('.search-result').forEach(b=>b.onclick=()=>selectSearch(items[+b.dataset.index]))}
function selectSearch(o){$('#searchResults').classList.remove('open');$('#searchInput').value=o.name||o.id;if(o.kind==='coords'){setMode('equatorial');animateView(o.ra*15,o.dec,20)}else focusObject(o)}
function toggle(key,button,switchEl){state[key]=!state[key];if(button){button.classList.toggle('active',state[key]);button.setAttribute('aria-pressed',state[key])}if(switchEl)switchEl.checked=state[key];render();saveHash()}
function closePanel(id){if(id==='detailsPanel')detailImageToken++;const el=$('#'+id);if(id==='controlPanel')el.classList.add('closed');else el.classList.remove('open');el.setAttribute('aria-hidden','true')}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function saveHash(){const p=new URLSearchParams({m:state.mode,lon:state.centerLon.toFixed(3),lat:state.centerLat.toFixed(3),fov:state.fov.toFixed(2),ml:state.magLimit.toFixed(1),olat:state.lat.toFixed(4),olon:state.lon.toFixed(4),t:state.time.toISOString()});history.replaceState(null,'','#'+p.toString())}
function loadHash(){if(!location.hash)return;try{const p=new URLSearchParams(location.hash.slice(1));if(['horizontal','equatorial'].includes(p.get('m')))state.mode=p.get('m');for(const [k,key,a,b] of [['lon','centerLon',-360,360],['lat','centerLat',-90,90],['fov','fov',3,130],['ml','magLimit',1,6.5],['olat','lat',-90,90],['olon','lon',-180,180]]){const v=+p.get(k);if(Number.isFinite(v))state[key]=clamp(v,a,b)}const t=new Date(p.get('t'));if(!isNaN(t))state.time=t}catch{}}
function reset(){state.centerLon=state.mode==='horizontal'?180:0;state.centerLat=state.mode==='horizontal'?35:0;state.fov=70;render();saveHash()}
function installEvents(){window.addEventListener('resize',resize);canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,lon:state.centerLon,lat:state.centerLat,moved:false}});canvas.addEventListener('pointermove',e=>{state.pointer={x:e.clientX,y:e.clientY};if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>3)drag.moved=true;const scale=state.fov/Math.max(280,h);state.centerLon=norm360(drag.lon-dx*scale);state.centerLat=clamp(drag.lat+dy*scale,-89.5,89.5);render()}else updatePointerReadout(e)});canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const hit=hitTargets.filter(t=>Math.hypot(t.x-x,t.y-y)<=t.r).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(hit)showDetails(hit.object)}drag=null;saveHash()});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();state.fov=clamp(state.fov*Math.exp(e.deltaY*.0012),3,130);render();saveHash()},{passive:false});canvas.addEventListener('dblclick',e=>{const r=canvas.getBoundingClientRect(),v=unproject(e.clientX-r.left,e.clientY-r.top),ll=vecLonLat(v);animateView(ll.lon,ll.lat,state.fov*.55)});
const touches=new Map();canvas.addEventListener('touchstart',e=>{for(const t of e.changedTouches)touches.set(t.identifier,{x:t.clientX,y:t.clientY});if(touches.size===2){const a=[...touches.values()];pinch={dist:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),fov:state.fov}}},{passive:true});canvas.addEventListener('touchmove',e=>{for(const t of e.changedTouches)touches.set(t.identifier,{x:t.clientX,y:t.clientY});if(touches.size===2&&pinch){const a=[...touches.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);state.fov=clamp(pinch.fov*pinch.dist/d,3,130);render()}},{passive:true});canvas.addEventListener('touchend',e=>{for(const t of e.changedTouches)touches.delete(t.identifier);if(touches.size<2)pinch=null});
$('#searchInput').addEventListener('input',e=>showSearchResults(search(e.target.value)));$('#searchForm').addEventListener('submit',e=>{e.preventDefault();const r=search($('#searchInput').value);if(r.length)selectSearch(r[0]);else toast('No match in the offline catalog')});document.addEventListener('click',e=>{if(!e.target.closest('.search'))$('#searchResults').classList.remove('open')});
$('#controlsButton').onclick=()=>$('#controlPanel').classList.toggle('closed');$('#timeButton').onclick=()=>$('#controlPanel').classList.toggle('closed');$('#modeButton').onclick=()=>setMode(state.mode==='horizontal'?'equatorial':'horizontal');$$('#modeSelect button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$('#gridButton').onclick=()=>toggle('grid',$('#gridButton'));$('#constellationButton').onclick=()=>toggle('constellations',$('#constellationButton'));$('#dsoButton').onclick=()=>toggle('dso',$('#dsoButton'));$('#labelsButton').onclick=()=>toggle('labels',$('#labelsButton'));$('#nightButton').onclick=()=>{toggle('night',$('#nightButton'));document.body.classList.toggle('night',state.night)};$('#resetButton').onclick=reset;$('#aboutButton').onclick=()=>{$('#aboutPanel').classList.add('open');$('#aboutPanel').setAttribute('aria-hidden','false')};$$('[data-close]').forEach(b=>b.onclick=()=>closePanel(b.dataset.close));
$('#magLimit').oninput=e=>{state.magLimit=+e.target.value;$('#magValue').textContent=state.magLimit.toFixed(1);render()};$('#starScale').oninput=e=>{state.starScale=+e.target.value/100;$('#scaleValue').textContent=e.target.value+'%';render()};$$('[data-time]').forEach(b=>b.onclick=()=>{state.time=new Date(state.time.getTime()+ +b.dataset.time);render();saveHash()});$('#nowButton').onclick=()=>{state.time=new Date();render();saveHash()};$('#playButton').onclick=()=>{state.playing=!state.playing;$('#playButton').textContent=state.playing?'❚❚ Pause':'▶ Play 120×'};
$('#applyLocationButton').onclick=()=>{state.lat=clamp(+$('#latitudeInput').value||0,-90,90);state.lon=clamp(+$('#longitudeInput').value||0,-180,180);$('#locationName').textContent='Manual coordinates';render();saveHash()};$('#locateButton').onclick=()=>{if(!navigator.geolocation)return toast('Geolocation is not supported');navigator.geolocation.getCurrentPosition(p=>{state.lat=p.coords.latitude;state.lon=p.coords.longitude;$('#latitudeInput').value=state.lat.toFixed(4);$('#longitudeInput').value=state.lon.toFixed(4);$('#locationName').textContent='Device location';render();saveHash();toast('Observer location updated')},()=>toast('Location permission denied — manual coordinates remain available'),{enableHighAccuracy:false,timeout:8000})};
$('#milkyWaySwitch').onchange=e=>{state.milkyWay=e.target.checked;render()};$('#horizonSwitch').onchange=e=>{state.hideBelow=e.target.checked;render()};$('#cardinalSwitch').onchange=e=>{state.cardinals=e.target.checked;render()};
$('#shareButton').onclick=async()=>{saveHash();try{await navigator.clipboard.writeText(location.href);toast('View link copied')}catch{prompt('Copy this offline view link',location.href)}};$('#fullscreenButton').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('.brand').onclick=e=>{e.preventDefault();reset()};
document.addEventListener('keydown',e=>{if(e.target.matches('input')){if(e.key==='Escape')e.target.blur();return}const k=e.key.toLowerCase();if(k==='/'){e.preventDefault();$('#searchInput').focus()}else if(k==='g')$('#gridButton').click();else if(k==='c')$('#constellationButton').click();else if(k==='d')$('#dsoButton').click();else if(k==='l')$('#labelsButton').click();else if(k==='h')$('#modeButton').click();else if(k==='n')$('#nightButton').click();else if(k==='r')reset();else if(k==='f')$('#fullscreenButton').click();else if(e.key==='Escape'){$$('.open').forEach(x=>x.classList.remove('open'));$('#searchResults').classList.remove('open')}});}
function updatePointerReadout(e){const r=canvas.getBoundingClientRect(),v=unproject(e.clientX-r.left,e.clientY-r.top),ll=vecLonLat(v);if(state.mode==='horizontal')$('#coordReadout').textContent=`Az ${ll.lon.toFixed(2)}° · Alt ${ll.lat.toFixed(2)}°`;else $('#coordReadout').textContent=`RA ${formatRA(ll.lon/15)} · Dec ${formatDec(ll.lat)}`}
function loop(now){const dt=now-lastFrame;lastFrame=now;if(state.playing){state.time=new Date(state.time.getTime()+dt*120);render()}requestAnimationFrame(loop)}
function init(){loadHash();$('#magLimit').value=state.magLimit;$('#magValue').textContent=state.magLimit.toFixed(1);$('#latitudeInput').value=state.lat.toFixed(4);$('#longitudeInput').value=state.lon.toFixed(4);$$('#modeSelect button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('#starCount').textContent=STAR_DATA.length;$('#dsoCount').textContent=DSO_DATA.length;$('#constCount').textContent=Object.keys(CONSTELLATION_LINES).length;const tours=['M31','M42','M45','M13','M51','M57','M104','NGC 7000','Sirius','Polaris'];$('#quickTour').innerHTML=tours.map(x=>`<button class="tour-chip" data-target="${x}">${x}</button>`).join('');$$('.tour-chip').forEach(b=>b.onclick=()=>{const o=[...DSO_DATA,...STAR_DATA.map(x=>({...x,id:x.name,kind:'star'}))].find(x=>(x.id||x.name)===b.dataset.target);if(o)focusObject({...o,kind:o.kind||'dso'})});installEvents();resize();requestAnimationFrame(loop);setTimeout(()=>$('#loadingScreen').classList.add('hidden'),450);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{});}
init();
})();
