/* Generated by tools/build_dso_image_index.py. Do not edit by hand. */
globalThis.DSO_IMAGE_INDEX = {
  "m101": [
    {
      "src": "images/dso/m101.jpg",
      "title": "A distinctly disorganised dwarf ",
      "alt": "A distinctly disorganised dwarf ",
      "credit": "GSFC",
      "source": "https://images.nasa.gov/details/hubble-peers-at-a-distinctly-disorganized-dwarf-galaxy_25568403123_o",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "m104": [
    {
      "src": "images/dso/m104.jpg",
      "title": "History of Hubble Space Telescope (HST)",
      "alt": "History of Hubble Space Telescope (HST)",
      "credit": "MSFC",
      "source": "https://images.nasa.gov/details/0700064",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "m106": [
    {
      "src": "images/dso/m106.jpg",
      "title": "Amateur and Professional Astronomers Team Up to Create a Cosmological Masterpiece",
      "alt": "Amateur and Professional Astronomers Team Up to Create a Cosmological Masterpiece",
      "credit": "GSFC",
      "source": "https://images.nasa.gov/details/GSFC_20171208_Archive_e001558",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "m31": [
    {
      "src": "images/dso/m31.jpg",
      "title": "Hubble's High-Definition Panoramic View of the Andromeda Galaxy",
      "alt": "Hubble's High-Definition Panoramic View of the Andromeda Galaxy",
      "credit": "GSFC",
      "source": "https://images.nasa.gov/details/GSFC_20171208_Archive_e000833",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "m51": [
    {
      "src": "images/dso/m51.jpg",
      "title": "A galactic sunflower",
      "alt": "A galactic sunflower",
      "credit": "GSFC",
      "source": "https://images.nasa.gov/details/hubble-sees-a-galactic-sunflower_21136469209_o",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "m64": [
    {
      "src": "images/dso/m64.jpg",
      "title": "History of Hubble Space Telescope (HST)",
      "alt": "History of Hubble Space Telescope (HST)",
      "credit": "MSFC",
      "source": "https://images.nasa.gov/details/0400392",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "m83": [
    {
      "src": "images/dso/m83.jpg",
      "title": "spiral galaxy M83",
      "alt": "spiral galaxy M83",
      "credit": "GSFC",
      "source": "https://images.nasa.gov/details/GSFC_20171208_Archive_e001262",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "m87": [
    {
      "src": "images/dso/m87.jpg",
      "title": "Spitzer Captures Messier 87",
      "alt": "The galaxy M87, imaged here by NASA's Spitzer Space Telescope, is home to a supermassive black hole that spews two jets of material out into space at nearly the speed of light.",
      "credit": "NASA/JPL-Caltech/IPAC/Event Horizon Telescope Collaboration / JPL",
      "source": "https://images.nasa.gov/details/PIA23122",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "m94": [
    {
      "src": "images/dso/m94.jpg",
      "title": "A Hubble View of Starburst Galaxy Messier 94",
      "alt": "A Hubble View of Starburst Galaxy Messier 94",
      "credit": "GSFC",
      "source": "https://images.nasa.gov/details/GSFC_20171208_Archive_e000526",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "ngc253": [
    {
      "src": "images/dso/ngc253.jpg",
      "title": "The Many Infrared Personalities of the Sculptor Galaxy",
      "alt": "The Sculptor galaxy, or NGC 253, is seen in a rainbow of infrared colors in this mosaic by NASA Wide-field Infrared Survey Explorer. The Sculptor galaxy can be seen by observers in the southern hemisphere with a pair of good binoculars.",
      "credit": "NASA/JPL-Caltech/UCLA / JPL",
      "source": "https://images.nasa.gov/details/PIA13440",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ],
  "ngc5128": [
    {
      "src": "images/dso/ngc5128.jpg",
      "title": "NGC 5128 Centaurus-A",
      "alt": "This ultraviolet image from NASA Galaxy Evolution Explorer is of NGC 5128 Centaurus-A. This unusual galaxy is believed to be the result of a collision of two normal galaxies.",
      "credit": "NASA/JPL-Caltech/SSC / JPL",
      "source": "https://images.nasa.gov/details/PIA07912",
      "license": "Review the source page. NASA content is generally available under NASA media usage guidelines, but third-party material may have separate rights."
    }
  ]
};
globalThis.DSO_IMAGE_FILES = [
  "./images/dso/m101.jpg",
  "./images/dso/m104.jpg",
  "./images/dso/m106.jpg",
  "./images/dso/m31.jpg",
  "./images/dso/m51.jpg",
  "./images/dso/m64.jpg",
  "./images/dso/m83.jpg",
  "./images/dso/m87.jpg",
  "./images/dso/m94.jpg",
  "./images/dso/ngc253.jpg",
  "./images/dso/ngc5128.jpg"
];
