#!/usr/bin/env python3
"""Build the browser/service-worker image index from images/dso.

Add images to images/dso and run this script. Optional sidecar JSON files with the
same basename can provide object aliases and attribution metadata.
"""
from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IMAGE_DIR = ROOT / "images" / "dso"
OUTPUT = ROOT / "dso-images.js"
SUPPORTED = {".webp", ".jpg", ".jpeg", ".png", ".avif"}


def key(value: str) -> str:
    value = unicodedata.normalize("NFKD", value or "").encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def display_name(stem: str) -> str:
    return re.sub(r"[-_]+", " ", stem).strip().title()


def read_metadata(path: Path) -> dict:
    candidates = [path.with_suffix(".json"), path.with_name(path.stem + ".metadata.json")]
    for candidate in candidates:
        if candidate.exists():
            try:
                data = json.loads(candidate.read_text(encoding="utf-8"))
                return data if isinstance(data, dict) else {}
            except (OSError, json.JSONDecodeError) as exc:
                print(f"Warning: cannot read {candidate.relative_to(ROOT)}: {exc}")
    return {}


def main() -> None:
    IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    index: dict[str, list[dict]] = {}
    files: list[str] = []

    for path in sorted(IMAGE_DIR.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in SUPPORTED:
            continue

        rel = path.relative_to(ROOT).as_posix()
        files.append("./" + rel)
        meta = read_metadata(path)
        numbered_base = re.sub(r"(?:[-_]\d+)$", "", path.stem)
        object_names = meta.get("objects", meta.get("object", []))
        if isinstance(object_names, str):
            object_names = [object_names]
        if not isinstance(object_names, list):
            object_names = []

        lookup_names = [path.stem, numbered_base, *[str(x) for x in object_names]]
        entry = {
            "src": rel,
            "title": str(meta.get("title") or display_name(numbered_base)),
            "alt": str(meta.get("alt") or meta.get("title") or display_name(numbered_base)),
            "credit": str(meta.get("credit") or "Local offline image"),
            "source": str(meta.get("source") or ""),
            "license": str(meta.get("license") or ""),
        }

        for name in lookup_names:
            lookup_key = key(name)
            if not lookup_key:
                continue
            bucket = index.setdefault(lookup_key, [])
            if not any(item["src"] == rel for item in bucket):
                bucket.append(entry)

    payload = (
        "/* Generated by tools/build_dso_image_index.py. Do not edit by hand. */\n"
        f"globalThis.DSO_IMAGE_INDEX = {json.dumps(index, ensure_ascii=False, indent=2)};\n"
        f"globalThis.DSO_IMAGE_FILES = {json.dumps(files, ensure_ascii=False, indent=2)};\n"
    )
    OUTPUT.write_text(payload, encoding="utf-8")
    print(f"Indexed {len(files)} image(s) under {len(index)} lookup key(s).")


if __name__ == "__main__":
    main()
